services:
  web:
    build:
      context: ./
    ports: 
      - "5000:${FASTLADDER_PORT:-5000}"
    environment:
      DATABASE_URL: "postgresql://${DB_USERNAME:-fastladder}:${DB_PASSWORD:-fastladder}@db/${DB_NAME:-fastladder}"
      PORT: "${FASTLADDER_PORT:-5000}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:?PLEASE SET SECRET_KEY_BASE IN .env FILE}"
    command: bash -c "./bin/rails db:create db:migrate && foreman start"
    restart: always
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: "${DB_USERNAME:-fastladder}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-fastladder}"
      POSTGRES_DB: "${DB_NAME:-fastladder}"
    volumes:
      - "${DB_VOLUME_PATH:-./DB_DATA}:/var/lib/postgresql/data"
