version: '3'
services:
  web:
    build:
      context: ./
    depends_on:
      - db
    ports: 
      - 5000:5000
    environment:
      DATABASE_URL: mysql2://root@db/fastladder
      PORT: "5000"
      SECRET_KEY_BASE: PLEASE_CHANGE_ME
    command: bash -c "./bin/rails db:create db:migrate && foreman start"
    restart: always
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysqldata:/var/lib/mysql
